{{- $fullName := include "app.fullname" . -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-legacy
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: {{ $fullName }}-legacy-green
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    cloud-platform.justice.gov.uk/ignore-external-dns-weight: "true"
    allow-duplicate-host: "true"
    allowed-duplicate-ns: "operations-engineering-reports-prod,github-community-prod"
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "100"
    nginx.ingress.kubernetes.io/affinity: "cookie"
spec:
  ingressClassName: "default"
  tls:
    - hosts:
        - "operations-engineering-reports.cloud-platform.service.justice.gov.uk"
      secretName: "ssl-certificate"
  rules:
    - host: "operations-engineering-reports.cloud-platform.service.justice.gov.uk"
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}-legacy
                port:
                  number: 80
