apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: 4567
      targetPort: http
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
