---
services:
  database:
    image: docker.io/postgres:17-alpine@sha256:3406990b6e4c7192317b6fdc5680498744f6142f01f0287f4ee0420d8c74063c
    environment:
      - POSTGRES_DB=admin
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"
      interval: 1s
      timeout: 5s
      retries: 5

  app:
    image: "${CONTAINER_IMAGE_NAME:-ministryofjustice/github-community}:${CONTAINER_IMAGE_TAG:-local}"
    platform: linux/amd64
    environment:
      # Flask
      - APP_SECRET_KEY=dev
      - FLASK_DEBUG=false

      # Postgres
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_DB=admin
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

      # Auth0
      - AUTH0_CLIENT_ID=dev
      - AUTH0_CLIENT_SECRET=dev
      - AUTH0_DOMAIN=operations-engineering.eu.auth0.com

      # App
      - PHASE_BANNER_TEXT=LOCAL DEV
      - ENV=local

      # GitHub
      - ADMIN_GITHUB_TOKEN=test
      - GITHUB_APP_INSTALLATION_ID=12345678

      # Local
      - LOGGING_LEVEL=DEBUG
      - AUTH_ENABLED=false
      - ADD_STUB_VALUES_TO_DATABASE=true
    ports:
      - "4567:4567"
    depends_on:
      database:
        condition: service_healthy

  db-seed:
    image: docker.io/postgres:17-alpine@sha256:3406990b6e4c7192317b6fdc5680498744f6142f01f0287f4ee0420d8c74063c
    depends_on:
      - database
    environment:
      PGPASSWORD: admin
    networks:
      - default
    volumes:
      - ./db-init:/db-init
    entrypoint: >
      sh -c '
        echo "Waiting for database...";
        until pg_isready -h database -p 5432 -U admin; do sleep 1; done;
        echo "Waiting for Alembic migrations...";
        until psql -h database -U admin -d admin -c "SELECT 1 FROM alembic_version" >/dev/null 2>&1; do sleep 1; done;
        echo "Running stub SQL files...";
        psql -h database -U admin -d admin -f "/db-init/01-stub-repository-standards-data.sql";
        echo "Database seeding complete.";
      '
