---
version: 2

multi-ecosystem-groups:
  app-and-infrastructure:
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ":dependabot: app-and-infrastructure"
      include: "scope"
  ci-cd:
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ":dependabot: ci-cd"
      include: "scope"

updates:
  - package-ecosystem: "uv"
    directory: "/"
    cooldown:
      default-days: 14
    schedule:
      interval: "weekly"
    patterns: ["*"]
    multi-ecosystem-group: "app-and-infrastructure"
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker"
    directory: "/"
    cooldown:
      default-days: 14
    schedule:
      interval: "weekly"
    patterns: ["*"]
    multi-ecosystem-group: "app-and-infrastructure"
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker-compose"
    directory: "/contrib"
    cooldown:
      default-days: 14
    schedule:
      interval: "weekly"
    patterns: ["*"]
    multi-ecosystem-group: "app-and-infrastructure"
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "devcontainers"
    directory: "/"
    cooldown:
      default-days: 14
    schedule:
      interval: "weekly"
    patterns: ["*"]
    multi-ecosystem-group: "ci-cd"
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    cooldown:
      default-days: 14
    schedule:
      interval: "weekly"
    patterns: ["*"]
    multi-ecosystem-group: "ci-cd"
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "pre-commit"
    directory: "/"
    cooldown:
      default-days: 14
    schedule:
      interval: "weekly"
    patterns: ["*"]
    multi-ecosystem-group: "ci-cd"
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
