---
services:
  database:
    image: public.ecr.aws/docker/library/postgres:14-alpine
    environment:
      - POSTGRES_DB=admin
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    image: github-community
    environment:
      # Flask
      - APP_SECRET_KEY=dev
      - FLASK_DEBUG=false

      # Postgres
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_DB=admin
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

      # Auth0
      - AUTH0_CLIENT_ID=dev
      - AUTH0_CLIENT_SECRET=dev
      - AUTH0_DOMAIN=operations-engineering.eu.auth0.com

      # App
      - PHASE_BANNER_TEXT=LOCAL DEV

      # CircleCI
      - CIRCLECI_TOKEN=test
      - CIRCLECI_COST_PER_CREDIT=0.0005

      # GitHub
      - ADMIN_GITHUB_TOKEN=test
      - GITHUB_APP_INSTALLATION_ID=12345678

      # Local
      - LOGGING_LEVEL=DEBUG
      - AUTH_ENABLED=false
      - ADD_STUB_VALUES_TO_DATABASE=true
    ports:
      - "4567:4567"
    depends_on:
      database:
        condition: service_healthy
