app:
  ingress:
    hosts:
      - "github-community.cloud-platform.service.justice.gov.uk"
      - "github-community.service.justice.gov.uk"
      - "operations-engineering-reports.cloud-platform.service.justice.gov.uk"
      - "operations-engineering-reports-prod.cloud-platform.service.justice.gov.uk"

  deployment:
    replicaCount: 1
    env:
      AUTH0_DOMAIN: "github-community.eu.auth0.com"
      SENTRY_ENV: "production"
      FLASK_DEBUG: true
      PHASE_BANNER_TEXT: "ALPHA"
      AUTH_ENABLED: true
