---
name: ♻️ Tests

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        id: checkout
        with:
          persist-credentials: false

      - name: Set Up UV
        id: setup_uv
        uses: astral-sh/setup-uv@4959332f0f014c5280e7eac8b70c90cb574c9f9b # v6.6.0
        with:
          activate-environment: true

      - name: Sync Dependencies
        id: sync_dependencies
        run: make uv-sync

      - name: Run Tests
        id: run_tests
        run: make test
