---
name: ♻️ Tests

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        id: checkout
        with:
          persist-credentials: false

      - name: Set up Python
        id: setup_python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: 3.12
          cache: pipenv

      - name: Install Pipenv
        id: install_pipenv
        run: pip install pipenv

      - name: Verify Pipfile.lock
        id: pipenv_verify
        run: pipenv verify

      - name: Install Dependencies
        id: install_dependencies
        run: pipenv install --dev

      - name: Run Unit Tests
        id: run_tests
        run: pipenv run tests

      - name: Show Coverage
        id: show_coverage
        run: pipenv run tests_report
